// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Delete_Table_Games : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Delete_Table_Games));
        
        string IMigrationMetadata.Id
        {
            get { return "202010242128221_Delete_Table_Games"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
