// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Add_Tables_UserAccountActivities_And_AccountPhotoActivities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Tables_UserAccountActivities_And_AccountPhotoActivities));
        
        string IMigrationMetadata.Id
        {
            get { return "202011090119008_Add_Tables_UserAccountActivities_And_AccountPhotoActivities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
