// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Modify_Table_Games_Add_ForeignKey_For_Team1_And_Team2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modify_Table_Games_Add_ForeignKey_For_Team1_And_Team2));
        
        string IMigrationMetadata.Id
        {
            get { return "202012300013116_Modify_Table_Games_Add_ForeignKey_For_Team1_And_Team2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
