// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Remove_Dependency_Between_AspNetUsers_And_NewBookingNotifications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Remove_Dependency_Between_AspNetUsers_And_NewBookingNotifications));
        
        string IMigrationMetadata.Id
        {
            get { return "202011110253530_Remove_Dependency_Between_AspNetUsers_And_NewBookingNotifications"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
