// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Readd_Dependency_Of_Tables_Accounts_And_NewBookingNotifications_To_AspNetUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Readd_Dependency_Of_Tables_Accounts_And_NewBookingNotifications_To_AspNetUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "202011110325558_Readd_Dependency_Of_Tables_Accounts_And_NewBookingNotifications_To_AspNetUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
