// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CourtModel_Add_AdditionalInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CourtModel_Add_AdditionalInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "202001260306542_CourtModel_Add_AdditionalInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
