// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add__DevHelpers_SP_DeleteUserByUserName_Stored_Proc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add__DevHelpers_SP_DeleteUserByUserName_Stored_Proc));
        
        string IMigrationMetadata.Id
        {
            get { return "202111261644414_Add__DevHelpers_SP_DeleteUserByUserName_Stored_Proc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
