// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModifyTable_Tournaments_AddColumns_DefaultCourtId_and_LogoId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifyTable_Tournaments_AddColumns_DefaultCourtId_and_LogoId));
        
        string IMigrationMetadata.Id
        {
            get { return "202307040900167_ModifyTable_Tournaments_AddColumns_DefaultCourtId_and_LogoId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
