// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Link_Chat_Tables_To_PhotoModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Link_Chat_Tables_To_PhotoModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202308231524509_Link_Chat_Tables_To_PhotoModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
