// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModifyTable_GamePlayers_RemoveColumn_IsEjected_AddColumn_EjectionStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifyTable_GamePlayers_RemoveColumn_IsEjected_AddColumn_EjectionStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202306280921313_ModifyTable_GamePlayers_RemoveColumn_IsEjected_AddColumn_EjectionStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
