// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Make_VideoModel_Inherit_From_MultimediaModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Make_VideoModel_Inherit_From_MultimediaModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202308270410447_Make_VideoModel_Inherit_From_MultimediaModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
