// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModifyTable_Posts_ModifyColumn_AddedById_add_FK_reference_to_Accounts_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifyTable_Posts_ModifyColumn_AddedById_add_FK_reference_to_Accounts_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202308151047559_ModifyTable_Posts_ModifyColumn_AddedById_add_FK_reference_to_Accounts_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
