// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreatTable_AccountFlags : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatTable_AccountFlags));
        
        string IMigrationMetadata.Id
        {
            get { return "202310180606369_CreatTable_AccountFlags"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
