// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModifyTable_GameTeams_AddColumns_TimeoutsLeft_FullTimeoutsUsed_ShortTimeoutsUsed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifyTable_GameTeams_AddColumns_TimeoutsLeft_FullTimeoutsUsed_ShortTimeoutsUsed));
        
        string IMigrationMetadata.Id
        {
            get { return "202307010605358_ModifyTable_GameTeams_AddColumns_TimeoutsLeft_FullTimeoutsUsed_ShortTimeoutsUsed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
