// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Use_AccountModel_as_ChatParticipant_and_MessageParticipant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Use_AccountModel_as_ChatParticipant_and_MessageParticipant));
        
        string IMigrationMetadata.Id
        {
            get { return "202308241602177_Use_AccountModel_as_ChatParticipant_and_MessageParticipant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
