// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddTables_MemberFouls_Fouls_and_GameEvents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTables_MemberFouls_Fouls_and_GameEvents));
        
        string IMigrationMetadata.Id
        {
            get { return "202306241501535_AddTables_MemberFouls_Fouls_and_GameEvents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
