// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DropTable_ChatParticipants : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropTable_ChatParticipants));
        
        string IMigrationMetadata.Id
        {
            get { return "202308250530147_DropTable_ChatParticipants"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
