// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddTables_GameTeams_and_GamePlayers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTables_GameTeams_and_GamePlayers));
        
        string IMigrationMetadata.Id
        {
            get { return "202306261254435_AddTables_GameTeams_and_GamePlayers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
