// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Make_StatsSummary_Columns_FTP_FGP_and_ThreePP_nullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Make_StatsSummary_Columns_FTP_FGP_and_ThreePP_nullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202308181015210_Make_StatsSummary_Columns_FTP_FGP_and_ThreePP_nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
