// <auto-generated />
namespace DribblyAuthAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Move_Username_Column_From_PlayerModel_To_AccountModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Move_Username_Column_From_PlayerModel_To_AccountModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202308260725060_Move_Username_Column_From_PlayerModel_To_AccountModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
